name: D:\PROJ\btlib\env
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.14.0
  - debugpy=1.8.17
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib-inline=0.2.1
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.14.0
  - python-dateutil=2.9.0.post0
  - python-gil=3.14.0
  - python_abi=3.14
  - pywin32=311
  - pyzmq=27.1.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - git-filter-repo==2.47.0
      - idna==3.11
      - numpy==2.3.5
      - pandas==2.3.3
      - python-dotenv==1.2.1
      - pytz==2025.2
      - requests==2.32.5
      - tzdata==2025.2
      - urllib3==2.5.0
